WDIO Tests
tetianastetsyk/myWDIOtests pull request #1
Opened 2023-09-01 16:56 UTC by tetianastetsyk

Hi Artem! Please review my PR.
Thanks!

2023-09-02 08:52 UTC, 4rtemOv commented
Привіт, мій інвайт чи то заекспайрився чи ти його відмінила( можешь плз спробувати ще раз?

2023-09-02 08:56 UTC, 4rtemOv requested changes
Several small comments were left

2023-09-02 08:56 UTC, 4rtemOv commented on test/specs/test.e2e.js
> +        await browser.url(`https://www.saucedemo.com/`)
Great job!
Let's make your code better.
You can use beforeAll function - more about it here https://stackoverflow.com/questions/46799242/before-hook-before-all-test-cases-in-mocha

2023-09-02 08:56 UTC, 4rtemOv commented on test/specs/test.e2e.js
> +        await browser.url(`https://www.saucedemo.com/`)
`https://www.saucedemo.com/` can be added to the config as baseUrl - find and read about it here https://webdriver.io/uk/docs/configurationfile/

2023-09-03 10:38 UTC, ovartem approved these changes
well done

2023-09-03 10:56 UTC, merged